# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 371, 305))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.emailName = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.emailName.setObjectName("emailName")
        self.verticalLayout.addWidget(self.emailName)
        self.emailValue = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.emailValue.setObjectName("emailValue")
        self.verticalLayout.addWidget(self.emailValue)
        self.adresName = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.adresName.setObjectName("adresName")
        self.verticalLayout.addWidget(self.adresName)
        self.adresValue = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.adresValue.setObjectName("adresValue")
        self.verticalLayout.addWidget(self.adresValue)
        self.hawai = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.hawai.setObjectName("hawai")
        self.verticalLayout.addWidget(self.hawai)
        self.margherita = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.margherita.setChecked(True)
        self.margherita.setObjectName("margherita")
        self.verticalLayout.addWidget(self.margherita)
        self.capricciosa = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.capricciosa.setObjectName("capricciosa")
        self.verticalLayout.addWidget(self.capricciosa)
        self.quattro = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.quattro.setObjectName("quattro")
        self.verticalLayout.addWidget(self.quattro)
        self.checkCheese = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkCheese.setObjectName("checkCheese")
        self.verticalLayout.addWidget(self.checkCheese)
        self.order = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.order.setObjectName("order")
        self.verticalLayout.addWidget(self.order)
        self.ordered = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.ordered.setText("")
        self.ordered.setObjectName("ordered")
        self.verticalLayout.addWidget(self.ordered)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.emailName.setText(_translate("Dialog", "email"))
        self.adresName.setText(_translate("Dialog", "adres"))
        self.hawai.setText(_translate("Dialog", "Hawajska"))
        self.margherita.setText(_translate("Dialog", "Margherita"))
        self.capricciosa.setText(_translate("Dialog", "Capricciosa"))
        self.quattro.setText(_translate("Dialog", "Quattro formaggi"))
        self.checkCheese.setText(_translate("Dialog", "dodatkowy ser"))
        self.order.setText(_translate("Dialog", "Zamów"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
